version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omkar
      MYSQL_DATABASE: trello
      MYSQL_USER: omkar
      MYSQL_PASSWORD: omkar
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db